### ISSUE TITLE
Implement tests via npm test

### ISSUE THREAD

**Issue by klokan** [klokantech/gl-style-package-spec#8]
The standard npm test could be used instead of pushing the test to ./task/deploy.sh script (where it does not belong).

If tests should be started from a shell script - it should be probably renamed to run.sh or similar - as it is not only deploy which happens there

**Comment by jirik** [comment]
@klokan Should be implemented in [npm_test branch](https://github.com/klokantech/gl-style-package-spec/tree/npm_test) in commit 37565e9e2be594418b6d717eb68b310fc0a60ee3.
Please check [package.json](https://github.com/klokantech/gl-style-package-spec/blob/npm_test/package.json) if there is correct information (license, authors, etc.). I inspired at tileserver-gl's package.json.

Immediately after merging branch npm_test into master we need to update .travis.yml files in style repositories, because we need to run `run.sh` instead of `deploy.sh` as you suggested above.
